"use client";

import ProductLandingLayout from "@/components/our-product/ProductLandingLayout";

const productData = {
  name: "AI Exploration Kit",
  tagline: "Inspiring Tomorrow's Innovators",
  image: "/products-images/product2.jpg",
  overview: "Unveil the power of neural networks and machine vision with the AI Exploration Kit. Specially crafted for beginners, this kit provides a tangible introduction to artificial intelligence by combining smart camera modules, processing units, and drag-and-drop model training platforms. Students will explore object recognition, facial detection, gesture tracking, and autonomous path-following, giving them hands-on access to the technologies shaping the future.",
  whyChoose: [
    {
      title: "Edge Computer Vision",
      description: "Perform object detection locally at high speed without relying on online cloud processors.",
      icon: "cpu" as const
    },
    {
      title: "No-Code ML Training",
      description: "Train models in under 5 minutes using intuitive web interfaces and transfer learning methods.",
      icon: "layers" as const
    },
    {
      title: "Engaging Visuals",
      description: "Direct visual feedback on smart cameras makes complex mathematical AI operations fun and understandable.",
      icon: "grad" as const
    }
  ],
  features: [
    {
      title: "Smart Camera Module",
      description: "Equipped with onboard AI algorithms for facial tracking, line sorting, and color classification."
    },
    {
      title: "High-Speed Processor Board",
      description: "Dedicated coprocessor designed to calculate matrix operations in real time."
    },
    {
      title: "Integrated LCD Panel",
      description: "Shows live image streams, classification scores, and diagnostic reports locally."
    },
    {
      title: "Block-Based AI Coding",
      description: "Students learn how AI decisions work by creating logical flows using custom block programming elements."
    }
  ],
  insideKit: [
    {
      name: "AI Smart Vision Camera",
      quantity: "1 Unit",
      description: "Camera sensor with integrated neural network processor and LED indicators."
    },
    {
      name: "2.4-Inch TFT LCD Screen",
      quantity: "1 Unit",
      description: "Shows live camera preview feed and bounding boxes generated by algorithms."
    },
    {
      name: "Image Classification Blocks",
      quantity: "1 Set",
      description: "Physical sorting blocks used for testing and debugging transfer learning runs."
    },
    {
      name: "MicroSD Card with Preloaded Models",
      quantity: "1 Unit",
      description: "Holds neural models for quick sorting runs out of the box."
    },
    {
      name: "Connecting USB-C Telemetry Cable",
      quantity: "2 Units",
      description: "Transmits serial programming data and charges systems."
    }
  ],
  learningOutcomes: [
    "Introduction to Neural Networks",
    "Computer vision color extraction",
    "Classification confidence scores",
    "On-device neural inference concepts",
    "Logic rules based on AI triggers",
    "Model training dataset collection"
  ],
  projects: [
    {
      title: "Autonomous Sorting Trash Bin",
      description: "Build a waste bin that classifies waste into biodegradable or recyclable and opens corresponding lids.",
      complexity: "Beginner" as const
    },
    {
      title: "Facial-Recognition Smart Door",
      description: "Program a locking servo to open only when a certified student face is recognized with high confidence.",
      complexity: "Intermediate" as const
    },
    {
      title: "Gesture-Controlled Robotic Drive",
      description: "Control motors using hand signs detected by the vision processor, executing custom directional patterns.",
      complexity: "Advanced" as const
    }
  ],
  specifications: [
    { label: "Target Age", value: "14+ Years" },
    { label: "Recommended Class", value: "Class 9 - College" },
    { label: "Core Sensor", value: "OmniVision Camera Sensor (HD)" },
    { label: "Onboard AI Chip", value: "Edge AI Neural Network Coprocessor" },
    { label: "Supported Languages", value: "Block-AI, Python, microPython" },
    { label: "Hardware Memory", value: "Pre-installed 16GB High-Speed Class 10 SD" },
    { label: "Warranty Support", value: "1 Year Manufacturer Warranty" }
  ],
  gallery: [
    "/products-images/product2.jpg",
    "/products-images/product2.jpg",
    "/products-images/product2.jpg"
  ],
  faqs: [
    {
      question: "Can we load custom trained TensorFlow models onto the kit?",
      answer: "Yes. Our conversion utility allows you to port light MobileNet or TensorFlow Lite models directly onto the SD card."
    },
    {
      question: "Does this require a powerful computer to train models?",
      answer: "No. Model training runs on our web-based transfer learning tool which processes datasets directly inside your web browser."
    },
    {
      question: "Is this kit compatible with Python?",
      answer: "Yes, advanced students can write native Python scripts to interface with the camera and retrieve inference structures."
    }
  ],
  related: [
    {
      name: "IoT Training Kit",
      image: "/products-images/product1.jpg",
      slug: "iot-training-kit",
      tagline: "Empower your ideas with IoT innovation"
    },
    {
      name: "Robotics Starter Kit",
      image: "/products-images/robotics-starter-kit.png",
      slug: "robotics-starter-kit",
      tagline: "Build smart robotic systems easily"
    },
    {
      name: "AI Mechatronics Lab",
      image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=1200&auto=format&fit=crop",
      slug: "ai-mechatronics-lab",
      tagline: "Advanced AI and mechatronics lab integration setup"
    }
  ]
};

export default function AiExplorationKitPage() {
  return <ProductLandingLayout {...productData} />;
}
